### ISSUE TITLE
lean源码openwrt 4.19内核 X86-64 改版KPR Plus 更新最新规则导致整个kpr崩溃的问题

### ISSUE THREAD

**Issue by firker** [houzi-/CDN#2]
lean源码openwrt 4.19内核 X86-64 
改版KPR Plus 
昨天9.4日上午更新的规则没问题，今天上午更新主koolproxy规则后，会出现程序停止运行的情况，但是取消每日规则的勾选，则可以启动，否则无法启动。替换之前的koolproxy规则则没有问题，只要不更新最新的koolproxy规则，则没有问题，是否是改版的kpr plus不再使用大佬的规则  ？

**Comment by hplee0120** [comment]
差不多的问题，由于现在x86 openwrt没有原生的kpr，魔改的kpr规则太多误杀也多。所以找了个旧的kp源码3.8.4修改新规则地址后编译后一直原本是可用的，最近更新后只要一开启静态规则插件就会停止运行。无论是原来的3.8.4还是替换二进制文件后的3.8.5都一样。日志如下
Mon Sep  7 04:15:26 2020 user.notice root: koolproxy has started.
Mon Sep  7 04:15:27 2020 daemon.info koolproxy[2790]: koolproxy v3.8.5
Mon Sep  7 04:15:27 2020 daemon.err koolproxy[2790]: Assertion failed: length >= 2 (/home/houzi-/develop/KoolProxy/src/adblock/adblock.c: rule_to_regex: 1000)
Mon Sep  7 04:15:27 2020 daemon.info koolproxy[2790]: listen port=3000
Mon Sep  7 04:15:27 2020 daemon.info koolproxy[2790]: log level=4
Mon Sep  7 04:15:27 2020 daemon.info koolproxy[2790]: thread count=4
Mon Sep  7 04:15:27 2020 daemon.info koolproxy[2790]: work path=/
Mon Sep  7 04:15:27 2020 daemon.info koolproxy[2790]: program path=/usr/share/koolproxy/koolproxy
Mon Sep  7 04:15:27 2020 daemon.info koolproxy[2790]: data path=/usr/share/koolproxy/data
Mon Sep  7 04:15:27 2020 daemon.info koolproxy[2790]: ttl mode=160
Mon Sep  7 04:15:27 2020 daemon.info koolproxy[2790]: ttl port=0
Mon Sep  7 04:15:27 2020 daemon.info koolproxy[2790]: mark mode=1
Mon Sep  7 04:15:27 2020 daemon.info koolproxy[2790]: max fd=131070
Mon Sep  7 04:15:27 2020 daemon.info koolproxy[2790]: init adblock engine
Mon Sep  7 04:15:27 2020 daemon.info koolproxy[2790]: load normal rule: /usr/share/koolproxy/data/rules/koolproxy.txt

**Comment by hplee0120** [comment]
刚推送9月6号规则后正常了

**Comment by Karmylr** [comment]
kp不适用于lean的openwrt哈
