### ISSUE TITLE
小白请教kp.dat问题

### ISSUE THREAD

**Issue by JimLee1996** [houzi-/CDN#3]
之前尝试使用乘风的视频规则只做kp.dat文件，但是不知道具体的数据结构，请教大佬是怎么操作来更新规则的

**Comment by houzi-** [comment]
更新结构这样的，每个更新的规则都由md5值控制，每次更新KP都需要调用md5。EP：fanboy.txt你放在`http://rules.xxxx.com/fanboy.txt `，因此你这个更新服务器上也要对应放上`http://rules.xxxx.com/fanboy.txt.md5`
这个md5文件，KP才能自动识别更新。生成这个文件请看仓库的
[md5.sh](https://raw.githubusercontent.com/houzi-/CDN/master/md5.sh)

**Comment by JimLee1996** [comment]
原来如此～谢谢！
